import { reactive } from 'vue'

export const estadoAtividades = reactive({
  lista: [
    //#region MATEMÁTICA

    //#region ADIÇÃO
    {
      id: 1,
      titulo: 'Adição',
      imagem: '/atividades/Matematica/Adicao/atividadeAdicao1.png',
      arquivo: '/atividades/Matematica/Adicao/atividadeAdicao1.pdf',
      materia: 'Matemática',
      conteudo: 'Adição',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 2,
      titulo: 'Adição',
      imagem: '/atividades/Matematica/Adicao/Soma1.jpeg',
      arquivo: '/atividades/Matematica/Adicao/semPDFporEnquanto.pdf',
      materia: 'Matemática',
      conteudo: 'Adição',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 3,
      titulo: 'Adição',
      imagem: '/atividades/Matematica/Adicao/Soma2.jpeg',
      arquivo: '/atividades/Matematica/Adicao/semPDFporEnquanto.pdf',
      materia: 'Matemática',
      conteudo: 'Adição',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 4,
      titulo: 'Adição',
      imagem: '/atividades/Matematica/Adicao/Soma3.jpeg',
      arquivo: '/atividades/Matematica/Adicao/semPDFporEnquanto.pdf',
      materia: 'Matemática',
      conteudo: 'Adição',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 5,
      titulo: 'Adição',
      imagem: '/atividades/Matematica/Adicao/Soma4.jpeg',
      arquivo: '/atividades/Matematica/Adicao/semPDFporEnquanto.pdf',
      materia: 'Matemática',
      conteudo: 'Adição',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 6,
      titulo: 'Adição',
      imagem: '/atividades/Matematica/Adicao/Soma5.jpeg',
      arquivo: '/atividades/Matematica/Adicao/semPDFporEnquanto.pdf',
      materia: 'Matemática',
      conteudo: 'Adição',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 7,
      titulo: 'Adição',
      imagem: '/atividades/Matematica/Adicao/Soma6.jpeg',
      arquivo: '/atividades/Matematica/Adicao/semPDFporEnquanto.pdf',
      materia: 'Matemática',
      conteudo: 'Adição',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 8,
      titulo: 'Adição',
      imagem: '/atividades/Matematica/Adicao/Soma7.jpeg',
      arquivo: '/atividades/Matematica/Adicao/semPDFporEnquanto.pdf',
      materia: 'Matemática',
      conteudo: 'Adição',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 9,
      titulo: 'Adição',
      imagem: '/atividades/Matematica/Adicao/Soma8.jpeg',
      arquivo: '/atividades/Matematica/Adicao/semPDFporEnquanto.pdf',
      materia: 'Matemática',
      conteudo: 'Adição',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 10,
      titulo: 'Adição',
      imagem: '/atividades/Matematica/Adicao/Soma9.jpeg',
      arquivo: '/atividades/Matematica/Adicao/semPDFporEnquanto.pdf',
      materia: 'Matemática',
      conteudo: 'Adição',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    //#endregion

    //#region ANÁLISE COMBINATÓRIA
    {
      id: 11,
      titulo: 'Análise combinatória',
      imagem: '/atividades/Matematica/Analise_combinatoria/atividadeAnalise1.png',
      arquivo: '/atividades/Matematica/Analise_combinatoria/atividadeAnalise1.pdf',
      materia: 'Matemática',
      conteudo: 'Análise combinatória',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    //#endregion

    //#region ÂNGULOS
    {
      id: 12,
      titulo: 'Ângulos',
      imagem: '/atividades/Matematica/Angulos/atividadeAngulo1.png',
      arquivo: '/atividades/Matematica/Angulos/atividadeAngulo1.pdf',
      materia: 'Matemática',
      conteudo: 'Ângulos',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 13,
      titulo: 'Ângulos',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Matematica/Angulos/atividadeAngulo1.docx',
      materia: 'Matemática',
      conteudo: 'Ângulos',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 14,
      titulo: 'Ângulos',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Matematica/Angulos/atividadeAngulo2.docx',
      materia: 'Matemática',
      conteudo: 'Ângulos',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    //#endregion

    //#region ÁREA
    {
      id: 15,
      titulo: 'Área',
      imagem: '/atividades/Matematica/Area/atividadeArea1.png',
      arquivo: '/atividades/Matematica/Area/atividadeArea1.pdf',
      materia: 'Matemática',
      conteudo: 'Área',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    //#endregion

    //#region SUBTRAÇÃO
    {
      id: 16,
      titulo: 'Subtração',
      imagem: '/atividades/Matematica/Subtracao/Subtração4.png',
      arquivo: '/atividades/Matematica/Subtração/SemNada.pdf',
      materia: 'Matemática',
      conteudo: 'Subtração',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 17,
      titulo: 'Subtração',
      imagem: '/atividades/Matematica/Subtracao/Subtração1.jpeg',
      arquivo: '/atividades/Matematica/SemNada.pdf',
      materia: 'Matemática',
      conteudo: 'Subtração',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 18,
      titulo: 'Subtração',
      imagem: '/atividades/Matematica/Subtracao/Subtração2.jpeg',
      arquivo: '/atividades/Matematica/SemNada.pdf',
      materia: 'Matemática',
      conteudo: 'Subtração',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 19,
      titulo: 'Subtração',
      imagem: '/atividades/Matematica/Subtracao/Subtração3.jpeg',
      arquivo: '/atividades/Matematica/SemNada.pdf',
      materia: 'Matemática',
      conteudo: 'Subtração',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    //#endregion

    //#region NÚMEROS
    {
      id: 20,
      titulo: 'Números',
      imagem: '/atividades/Matematica/Numeros/Numeros1.jpeg',
      arquivo: '/atividades/Matematica/Adicao/semPDFporEnquanto.pdf',
      materia: 'Matemática',
      conteudo: 'Números',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 21,
      titulo: 'Números',
      imagem: '/atividades/Matematica/Numeros/Numeros2.jpeg',
      arquivo: '/atividades/Matematica/Adicao/semPDFporEnquanto.pdf',
      materia: 'Matemática',
      conteudo: 'Números',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 22,
      titulo: 'Números',
      imagem: '/atividades/Matematica/Numeros/Numeros3.jpeg',
      arquivo: '/atividades/Matematica/Adicao/semPDFporEnquanto.pdf',
      materia: 'Matemática',
      conteudo: 'Números',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 23,
      titulo: 'Números',
      imagem: '/atividades/Matematica/Numeros/Numeros4.jpeg',
      arquivo: '/atividades/Matematica/Adicao/semPDFporEnquanto.pdf',
      materia: 'Matemática',
      conteudo: 'Números',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 24,
      titulo: 'Números',
      imagem: '/atividades/Matematica/Numeros/Numeros5.jpeg',
      arquivo: '/atividades/Matematica/Adicao/semPDFporEnquanto.pdf',
      materia: 'Matemática',
      conteudo: 'Números',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 25,
      titulo: 'Números',
      imagem: '/atividades/Matematica/Numeros/Numeros6.jpeg',
      arquivo: '/atividades/Matematica/Adicao/semPDFporEnquanto.pdf',
      materia: 'Matemática',
      conteudo: 'Números',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 26,
      titulo: 'Números',
      imagem: '/atividades/Matematica/Numeros/Numeros7.jpeg',
      arquivo: '/atividades/Matematica/Adicao/semPDFporEnquanto.pdf',
      materia: 'Matemática',
      conteudo: 'Números',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 27,
      titulo: 'Números',
      imagem: '/atividades/Matematica/Numeros/Numeros8.jpeg',
      arquivo: '/atividades/Matematica/Adicao/semPDFporEnquanto.pdf',
      materia: 'Matemática',
      conteudo: 'Números',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 28,
      titulo: 'Números',
      imagem: '/atividades/Matematica/Numeros/Numero9.png',
      arquivo: '/atividades/Matematica/Numeros/Numero9.pdf',
      materia: 'Matemática',
      conteudo: 'Números',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 29,
      titulo: 'Números',
      imagem: '/atividades/Matematica/Numeros/Numero10.png',
      arquivo: '/atividades/Matematica/Numeros/Numero10.pdf',
      materia: 'Matemática',
      conteudo: 'Números',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 30,
      titulo: 'Números',
      imagem: '/atividades/Matematica/Numeros/Numero11.png',
      arquivo: '/atividades/Matematica/Numeros/Numero11.pdf',
      materia: 'Matemática',
      conteudo: 'Números',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 31,
      titulo: 'Números',
      imagem: '/atividades/Matematica/Numeros/Numero12.png',
      arquivo: '/atividades/Matematica/Numeros/Numero12.pdf',
      materia: 'Matemática',
      conteudo: 'Números',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 32,
      titulo: 'Números',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Matematica/Numeros/Numero13.docx',
      materia: 'Matemática',
      conteudo: 'Números',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 33,
      titulo: 'Números',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Matematica/Numeros/Numero14.docx',
      materia: 'Matemática',
      conteudo: 'Números',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    //#endregion

    //#endregion

    //#region PORTUGUÊS

    //#region ALFABETIZAÇÃO
    {
      id: 34,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_A.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 35,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_B.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 36,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_C.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 37,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_D.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 38,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_E.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 39,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_F.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 40,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_G.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 41,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_H.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 42,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_I.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 43,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_J.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 44,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_K.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 45,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_L.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 46,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_M.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 47,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_N.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 48,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_O.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 49,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_P.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 50,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_Q.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 51,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_R.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 52,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_S.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 53,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_T.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 54,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_U.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 55,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_V.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 56,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_W.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 57,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_X.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 58,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_Y.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 59,
      titulo: 'Alfabetização',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Portugues/Alfabetizacao/Atividade_Z.docx',
      materia: 'Português',
      conteudo: 'Alfabetização',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    //#endregion

    //#endregion

    //#region QUÍMICA

    //#region Química Orgânica
    {
      id: 60,
      titulo: 'Química Orgânica',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Quimica/Quimica_organica/atividadeQuimica1.docx',
      materia: 'Química',
      conteudo: 'Química orgânica',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 61,
      titulo: 'Química Orgânica',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Quimica/Quimica_organica/atividadeQuimica2.docx',
      materia: 'Química',
      conteudo: 'Química orgânica',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 62,
      titulo: 'Química Orgânica',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Quimica/Quimica_organica/atividadeQuimica3.docx',
      materia: 'Química',
      conteudo: 'Química orgânica',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 63,
      titulo: 'Química Orgânica',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Quimica/Quimica_organica/atividadeQuimica4.docx',
      materia: 'Química',
      conteudo: 'Química orgânica',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 64,
      titulo: 'Química Orgânica',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Quimica/Quimica_organica/atividadeQuimica5.docx',
      materia: 'Química',
      conteudo: 'Química orgânica',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 65,
      titulo: 'Química Orgânica',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Quimica/Quimica_organica/atividadeQuimica6.docx',
      materia: 'Química',
      conteudo: 'Química orgânica',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 66,
      titulo: 'Química Orgânica',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Quimica/Quimica_organica/atividadeQuimica7.docx',
      materia: 'Química',
      conteudo: 'Química orgânica',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 67,
      titulo: 'Química Orgânica',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Quimica/Quimica_organica/atividadeQuimica8.docx',
      materia: 'Química',
      conteudo: 'Química orgânica',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 68,
      titulo: 'Química Orgânica',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Quimica/Quimica_organica/atividadeQuimica9.docx',
      materia: 'Química',
      conteudo: 'Química orgânica',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 69,
      titulo: 'Química Orgânica',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Quimica/Quimica_organica/atividadeQuimica10.docx',
      materia: 'Química',
      conteudo: 'Química orgânica',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 70,
      titulo: 'Química Orgânica',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Quimica/Quimica_organica/atividadeQuimica11.docx',
      materia: 'Química',
      conteudo: 'Química orgânica',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 71,
      titulo: 'Química Orgânica',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Quimica/Quimica_organica/atividadeQuimica12.docx',
      materia: 'Química',
      conteudo: 'Química orgânica',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 72,
      titulo: 'Química Orgânica',
      imagem: '/atividades/Quimica/Quimica_organica/atividadeQuimica13.png',
      arquivo: '/atividades/Quimica/Quimica_organica/atividadeQuimica13.pdf',
      materia: 'Química',
      conteudo: 'Química orgânica',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    //#endregion

    //#region ÁTOMO E MODELOS ATÔMICOS
    {
      id: 73,
      titulo: 'Átomo e modelos atômicos',
      imagem: '/atividades/Quimica/Atomo_e_modelos_atomicos/Atomo1.png',
      arquivo: '/atividades/Quimica/Atomo_e_modelos_atomicos/Atomo1.pdf',
      materia: 'Química',
      conteudo: 'Átomo e modelos atômicos',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 74,
      titulo: 'Átomo e modelos atômicos',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Quimica/Atomo_e_modelos_atomicos/Atomo2.docx',
      materia: 'Química',
      conteudo: 'Átomo e modelos atômicos',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 75,
      titulo: 'Átomo e modelos atômicos',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Quimica/Atomo_e_modelos_atomicos/Atomo3.docx',
      materia: 'Química',
      conteudo: 'Átomo e modelos atômicos',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 76,
      titulo: 'Átomo e modelos atômicos',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Quimica/Atomo_e_modelos_atomicos/Atomo4.docx',
      materia: 'Química',
      conteudo: 'Átomo e modelos atômicos',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 77,
      titulo: 'Átomo e modelos atômicos',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Quimica/Atomo_e_modelos_atomicos/Atomo5.docx',
      materia: 'Química',
      conteudo: 'Átomo e modelos atômicos',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    {
      id: 78,
      titulo: 'Átomo e modelos atômicos',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Quimica/Atomo_e_modelos_atomicos/Atomo6.docx',
      materia: 'Química',
      conteudo: 'Átomo e modelos atômicos',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    //#endregion

    //#endregion

    //#region GEOGRAFIA
    {
      id: 79,
      titulo: 'Geografia',
      imagem: '/SemImagem.png',
      arquivo: '/atividades/Quimica/Atomo_e_modelos_atomicos/Atomo6.docx',
      materia: 'Geografia',
      conteudo: 'Átomo e modelos atômicos',
      descricao: 'pipipipopopo',
      salvo: false,
    },
    //#endregion
  ],
})

// Exporta também com o nome antigo apontando para a lista reativa
export const atividades = estadoAtividades.lista

export default atividades
