import { reactive } from 'vue'

export const estadoPratica = reactive({
  lista: [
    // ANO NOVO
    {
      id: 600,
      titulo: 'Atividade',
      imagem: '/Imagens feriados/Ano Novo/AnoNovo_1.png',
      arquivo: '/Imagens feriados/Ano Novo/AnoNovo_1.pdf',
      data: 'Ano Novo',
      descricao: 'Atividade temática para celebração de Ano Novo na educação infantil.',
      salvo: false,
    },
    {
      id: 601,
      titulo: 'Complete o Desenho',
      imagem: '/Imagens feriados/Ano Novo/AnoNovo_2.jpg',
      arquivo: '/Imagens feriados/Ano Novo/AnoNovo_2.pdf',
      data: 'Ano Novo',
      descricao: 'Atividade de coordenação motora e escrita para o Ano Novo.',
      salvo: false,
    },
    {
      id: 602,
      titulo: 'Feliz Ano Novo',
      imagem: '/Imagens feriados/Ano Novo/AnoNovo_3.jpg',
      arquivo: '/Imagens feriados/Ano Novo/AnoNovo_3.pdf',
      data: 'Ano Novo',
      descricao: 'Desenho e atividade comemorativa de Feliz Ano Novo.',
      salvo: false,
    },

    // CARNAVAL
    {
      id: 603,
      titulo: 'Carnaval Ensino Fundamental 1',
      imagem: '/Imagens feriados/Carnaval/carnaval2.png',
      arquivo: '/Imagens feriados/Carnaval/carnaval2.pdf',
      data: 'Carnaval',
      descricao: 'Atividades pedagógicas lúdicas sobre o Carnaval.',
      salvo: false,
    },
    {
      id: 604,
      titulo: 'Atividades para o Carnaval 2022',
      imagem: '/Imagens feriados/Carnaval/carnaval1.jpg',
      arquivo: '/Imagens feriados/Carnaval/carnaval1.pdf',
      data: 'Carnaval',
      descricao: 'Exercícios práticos e coloridos de Carnaval.',
      salvo: false,
    },
    {
      id: 605,
      titulo: 'Festa de Carnaval',
      imagem: '/Imagens feriados/Carnaval/carnaval.png',
      arquivo: '/Imagens feriados/Carnaval/carnaval.pdf',
      data: 'Carnaval',
      descricao: 'Ilustrações e atividades artísticas para o Carnaval.',
      salvo: false,
    },
    {
      id: 608,
      titulo: 'Máscaras de Carnaval',
      imagem: '/Imagens feriados/Carnaval/carnaval3.jpg',
      arquivo: '/Imagens feriados/Carnaval/carnaval3.pdf',
      data: 'Carnaval',
      descricao: 'Pintura e confecção de máscaras carnavalescas.',
      salvo: false,
    },

    // DIA DA ESCOLA
    {
      id: 611,
      titulo: 'Minha Escola Querida',
      imagem: '/Imagens feriados/Dia da Escola/escola1.png',
      arquivo: '/Imagens feriados/Dia da Escola/escola1.pdf',
      data: 'Dia da Escola',
      descricao: 'Atividades de valorização do ambiente escolar e convívio.',
      salvo: false,
    },
    {
      id: 612,
      titulo: 'Dia da Escola - Educação Infantil',
      imagem: '/Imagens feriados/Dia da Escola/escola2.jpg',
      arquivo: '/Imagens feriados/Dia da Escola/escola2.pdf',
      data: 'Dia da Escola',
      descricao: 'Reconhecimento dos espaços e profissionais da escola.',
      salvo: false,
    },
    {
      id: 613,
      titulo: 'Conhecendo a Escola',
      imagem: '/Imagens feriados/Dia da Escola/escola3.png',
      arquivo: '/Imagens feriados/Dia da Escola/escola3.pdf',
      data: 'Dia da Escola',
      descricao: 'Atividades ilustradas sobre a rotina escolar.',
      salvo: false,
    },
    {
      id: 614,
      titulo: 'Celebrando a Escola',
      imagem: '/Imagens feriados/Dia da Escola/escola4.png',
      arquivo: '/Imagens feriados/Dia da Escola/escola4.pdf',
      data: 'Dia da Escola',
      descricao: 'Desenho e escrita para o Dia da Escola.',
      salvo: false,
    },
    {
      id: 615,
      titulo: 'O Papel da Escola',
      imagem: '/Imagens feriados/Dia da Escola/escola5.jpg',
      arquivo: '/Imagens feriados/Dia da Escola/escola5.pdf',
      data: 'Dia da Escola',
      descricao: 'Reflexão e atividades lúdicas sobre o aprendizado.',
      salvo: false,
    },

    // DIA DA ÁRVORE
    {
      id: 616,
      titulo: 'Preservando as Árvores',
      imagem: '/Imagens feriados/Dia da Árvore/arvore.jpg',
      arquivo: '/Imagens feriados/Dia da Árvore/arvore.pdf',
      data: 'Dia da Árvore',
      descricao: 'Conscientização ecológica e cuidados com a natureza.',
      salvo: false,
    },
    {
      id: 617,
      titulo: 'Partes da Árvore',
      imagem: '/Imagens feriados/Dia da Árvore/arvore2.png',
      arquivo: '/Imagens feriados/Dia da Árvore/arvore2.pdf',
      data: 'Dia da Árvore',
      descricao: 'Identificação de raiz, caule, folhas, flores e frutos.',
      salvo: false,
    },
    {
      id: 618,
      titulo: 'Dia da Árvore - Educação Infantil',
      imagem: '/Imagens feriados/Dia da Árvore/arvore3.jpg',
      arquivo: '/Imagens feriados/Dia da Árvore/arvore3.pdf',
      data: 'Dia da Árvore',
      descricao: 'Pintura a dedo e colagem temática de árvores.',
      salvo: false,
    },
    {
      id: 619,
      titulo: 'Cuidando da Natureza',
      imagem: '/Imagens feriados/Dia da Árvore/arvore4.jpg',
      arquivo: '/Imagens feriados/Dia da Árvore/arvore4.pdf',
      data: 'Dia da Árvore',
      descricao: 'Exercícios práticos sobre a importância do meio ambiente.',
      salvo: false,
    },
    {
      id: 620,
      titulo: 'A Importância das Árvores',
      imagem: '/Imagens feriados/Dia da Árvore/arvore5.png',
      arquivo: '/Imagens feriados/Dia da Árvore/arvore5.pdf',
      data: 'Dia da Árvore',
      descricao: 'Atividade ilustrada sobre oxigênio, sombra e fauna.',
      salvo: false,
    },
    {
      id: 621,
      titulo: 'Viva o Dia da Árvore',
      imagem: '/Imagens feriados/Dia da Árvore/arvore6.jpg',
      arquivo: '/Imagens feriados/Dia da Árvore/arvore6.pdf',
      data: 'Dia da Árvore',
      descricao: 'Atividade de colorir e completar a árvore.',
      salvo: false,
    },
    // DIA DAS CRIANÇAS
    {
      id: 622,
      titulo: 'Natureza e Sociedade - Dia das Crianças',
      imagem: '/Imagens feriados/Dia das crianças/criancas1.png',
      arquivo: '/Imagens feriados/Dia das crianças/criancas1.pdf',
      data: 'Dia das Crianças',
      descricao: 'Atividade interdisciplinar sobre direitos e brincadeiras infantis.',
      salvo: false,
    },
    {
      id: 623,
      titulo: 'Direitos da Criança',
      imagem: '/Imagens feriados/Dia das crianças/criancas2.jpg',
      arquivo: '/Imagens feriados/Dia das crianças/criancas2.pdf',
      data: 'Dia das Crianças',
      descricao: 'Exercícios lúdicos e desenhos para o Dia das Crianças.',
      salvo: false,
    },
    {
      id: 624,
      titulo: 'Brincadeiras e Jogos',
      imagem: '/Imagens feriados/Dia das crianças/criancas3.jpg',
      arquivo: '/Imagens feriados/Dia das crianças/criancas3.pdf',
      data: 'Dia das Crianças',
      descricao: 'Atividade de identificação de brinquedos e brincadeiras.',
      salvo: false,
    },
    // DIA DAS MÃES
    {
      id: 625,
      titulo: 'Cartão para o Dia das Mães 1',
      imagem: '/Imagens feriados/Dia das Maes/DiasDasMaes1.png',
      arquivo: '/Imagens feriados/Dia das Maes/DiasDasMaes1.pdf',
      data: 'Dia das Mães',
      descricao: 'Produção de mensagem e cartão afetivo para as mães.',
      salvo: false,
    },
    {
      id: 626,
      titulo: 'Cartão para o Dia das Mães 2',
      imagem: '/Imagens feriados/Dia das Maes/DiasDasMaes2.png',
      arquivo: '/Imagens feriados/Dia das Maes/DiasDasMaes2.pdf',
      data: 'Dia das Mães',
      descricao: 'Atividade de desenho e colagem para homenagear as mães.',
      salvo: false,
    },
    {
      id: 627,
      titulo: 'Poema do Dia das Mães',
      imagem: '/Imagens feriados/Dia das Maes/DiasDasMaes4.png',
      arquivo: '/Imagens feriados/Dia das Maes/DiasDasMaes4.pdf',
      data: 'Dia das Mães',
      descricao: 'Leitura, interpretação e pintura especial para o Dia das Mães.',
      salvo: false,
    },

    // DIA DO AMIGO
    {
      id: 629,
      titulo: 'Amigos Especiais',
      imagem: '/Imagens feriados/Dia do Amigo/amigos_atividade1.jpg',
      arquivo: '/Imagens feriados/Dia do Amigo/amigos_atividade1.pdf',
      data: 'Dia do Amigo',
      descricao: 'Atividade sobre amizade, respeito e convivência.',
      salvo: false,
    },
    {
      id: 630,
      titulo: 'Dia do Amigo e da Amizade',
      imagem: '/Imagens feriados/Dia do Amigo/amigos_atividade2.jpg',
      arquivo: '/Imagens feriados/Dia do Amigo/amigos_atividade2.pdf',
      data: 'Dia do Amigo',
      descricao: 'Exercícios práticos de empatia e união entre colegas.',
      salvo: false,
    },
    {
      id: 631,
      titulo: 'Amizade na Escola',
      imagem: '/Imagens feriados/Dia do Amigo/amigos_atividade3.jpg',
      arquivo: '/Imagens feriados/Dia do Amigo/amigos_atividade3.pdf',
      data: 'Dia do Amigo',
      descricao: 'Dinâmica e pintura coletiva sobre amigos.',
      salvo: false,
    },
    {
      id: 632,
      titulo: 'Complete a Palavra Amigo',
      imagem: '/Imagens feriados/Dia do Amigo/amigos_atividade4.jpg',
      arquivo: '/Imagens feriados/Dia do Amigo/amigos_atividade4.pdf',
      data: 'Dia do Amigo',
      descricao: 'Atividade de alfabetização e escrita da palavra amigo.',
      salvo: false,
    },
    // DIA DOS ANIMAIS
    {
      id: 633,
      titulo: 'Amigos da Natureza',
      imagem: '/Imagens feriados/Dia dos Animais/animais1.jpg',
      arquivo: '/Imagens feriados/Dia dos Animais/animais1.pdf',
      data: 'Dia dos Animais',
      descricao: 'Atividade sobre amizade, respeito e convivência.',
      salvo: false,
    },
    {
      id: 634,
      titulo: 'Dia do Amigo e da Amizade',
      imagem: '/Imagens feriados/Dia dos Animais/animais2.jpg',
      arquivo: '/Imagens feriados/Dia dos Animais/animais2.pdf',
      data: 'Dia dos Animais',
      descricao: 'Exercícios práticos de empatia e união entre colegas.',
      salvo: false,
    },
    {
      id: 635,
      titulo: 'Amizade na Escola',
      imagem: '/Imagens feriados/Dia dos Animais/animais3.jpg',
      arquivo: '/Imagens feriados/Dia dos Animais/animais3.pdf',
      data: 'Dia dos Animais',
      descricao: 'Dinâmica e pintura coletiva sobre amigos.',
      salvo: false,
    },
    {
      id: 636,
      titulo: 'Complete a Palavra Amigo',
      imagem: '/Imagens feriados/Dia dos Animais/animais4.png',
      arquivo: '/Imagens feriados/Dia dos Animais/animais4.pdf',
      data: 'Dia dos Animais',
      descricao: 'Atividade de alfabetização e escrita da palavra amigo.',
      salvo: false,
    },
    {
      id: 637,
      titulo: 'Complete a Palavra Amigo',
      imagem: '/Imagens feriados/Dia dos Animais/animais5.jpg',
      arquivo: '/Imagens feriados/Dia dos Animais/animais5.pdf',
      data: 'Dia dos Animais',
      descricao: 'Atividade de alfabetização e escrita da palavra amigo.',
      salvo: false,
    },
    // DIA DOS PAIS
    {
      id: 638,
      titulo: 'Dia dos Pais',
      imagem: '/Imagens feriados/Dia dos Pais/pais1.jpg',
      arquivo: '/Imagens feriados/Dia dos Pais/pais1.pdf',
      data: 'Dia dos Pais',
      descricao: 'Atividade sobre o Dia dos Pais.',
      salvo: false,
    },
    {
      id: 639,
      titulo: 'Mãe e Pai',
      imagem: '/Imagens feriados/Dia dos Pais/pais2.png',
      arquivo: '/Imagens feriados/Dia dos Pais/pais2.pdf',
      data: 'Dia dos Pais',
      descricao: 'Atividade sobre o Dia dos Pais.',
      salvo: false,
    },
    // DIA DOS POVOS INDÍGENAS
    {
      id: 640,
      titulo: 'Povos Indígenas',
      imagem: '/Imagens feriados/Dia dos Povos Indígenas/povosIndigenas1.jpg',
      arquivo: '/Imagens feriados/Dia dos Povos Indígenas/povosIndigenas1.pdf',
      data: 'Dia dos Povos Indígenas',
      descricao: 'Atividade para colorir.',
      salvo: false,
    },
    {
      id: 641,
      titulo: 'Povos Indígenas',
      imagem: '/Imagens feriados/Dia dos Povos Indígenas/povosIndigenas2.png',
      arquivo: '/Imagens feriados/Dia dos Povos Indígenas/povosIndigenas2.pdf',
      data: 'Dia dos Povos Indígenas',
      descricao: 'Atividade para escrever.',
      salvo: false,
    },
    {
      id: 642,
      titulo: 'Povos Indígenas',
      imagem: '/Imagens feriados/Dia dos Povos Indígenas/povosIndigenas3.jpg',
      arquivo: '/Imagens feriados/Dia dos Povos Indígenas/povosIndigenas3.pdf',
      data: 'Dia dos Povos Indígenas',
      descricao: 'Atividade para cortar e colar.',
      salvo: false,
    },
    // DIA INTERNACIONAL DA MULHER
    {
      id: 643,
      titulo: 'Dia Internacional da Mulher',
      imagem: '/Imagens feriados/Dia Internacional da Mulher/diaMulher1.jpg',
      arquivo: '/Imagens feriados/Dia Internacional da Mulher/diaMulher1.pdf',
      data: 'Dia Internacional da Mulher',
      descricao: 'Atividade para colorir.',
      salvo: false,
    },
    {
      id: 644,
      titulo: 'Dia Internacional da Mulher',
      imagem: '/Imagens feriados/Dia Internacional da Mulher/diaMulher2.jpg',
      arquivo: '/Imagens feriados/Dia Internacional da Mulher/diaMulher2.pdf',
      data: 'Dia Internacional da Mulher',
      descricao: 'Atividade para escrever.',
      salvo: false,
    },
    {
      id: 645,
      titulo: 'Dia Internacional da Mulher',
      imagem: '/Imagens feriados/Dia Internacional da Mulher/diaMulher3.png',
      arquivo: '/Imagens feriados/Dia Internacional da Mulher/diaMulher3.pdf',
      data: 'Dia Internacional da Mulher',
      descricao: 'Atividade para cortar e colar.',
      salvo: false,
    },
    {
      id: 646,
      titulo: 'Dia Internacional da Mulher',
      imagem: '/Imagens feriados/Dia Internacional da Mulher/diaMulher4.jpg',
      arquivo: '/Imagens feriados/Dia Internacional da Mulher/diaMulher4.pdf',
      data: 'Dia Internacional da Mulher',
      descricao: 'Atividade para pintar.',
      salvo: false,
    },
    // DIA MUNDIAL DO TRABALHO
    {
      id: 647,
      titulo: 'Dia Mundial do Trabalho',
      imagem: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho1.jpg',
      arquivo: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho1.pdf',
      data: 'Dia Mundial do Trabalho',
      descricao: 'Atividade para colorir.',
      salvo: false,
    },
    {
      id: 648,
      titulo: 'Dia Mundial do Trabalho',
      imagem: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho2.jpg',
      arquivo: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho2.pdf',
      data: 'Dia Mundial do Trabalho',
      descricao: 'Atividade para escrever.',
      salvo: false,
    },
    {
      id: 649,
      titulo: 'Dia Mundial do Trabalho',
      imagem: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho3.jpg',
      arquivo: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho3.pdf',
      data: 'Dia Mundial do Trabalho',
      descricao: 'Atividade para cortar e colar.',
      salvo: false,
    },
    {
      id: 650,
      titulo: 'Dia Mundial do Trabalho',
      imagem: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho4.png',
      arquivo: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho4.pdf',
      data: 'Dia Mundial do Trabalho',
      descricao: 'Atividade para pintar.',
      salvo: false,
    },
    {
      id: 651,
      titulo: 'Dia Mundial do Trabalho',
      imagem: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho5.jpeg',
      arquivo: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho5.pdf',
      data: 'Dia Mundial do Trabalho',
      descricao: 'Atividade para pintar.',
      salvo: false,
    },
    // DIA MUNDIAL DOS PROFESSORES
    {
      id: 652,
      titulo: 'Dia Mundial dos Professores',
      imagem: '/Imagens feriados/Dia Mundial dos Professores/diaProfessor1.jpg',
      arquivo: '/Imagens feriados/Dia Mundial dos Professores/diaProfessor1.pdf',
      data: 'Dia Mundial dos Professores',
      descricao: 'Atividade para colorir.',
      salvo: false,
    },
    {
      id: 653,
      titulo: 'Dia Mundial dos Professores',
      imagem: '/Imagens feriados/Dia Mundial dos Professores/diaProfessor2.png',
      arquivo: '/Imagens feriados/Dia Mundial dos Professores/diaProfessor2.pdf',
      data: 'Dia Mundial dos Professores',
      descricao: 'Atividade para escrever.',
      salvo: false,
    },
    // FESTA JUNINA
    {
      id: 654,
      titulo: 'Festa Junina',
      imagem: '/Imagens feriados/Festa junina/FestaJunina1.png',
      arquivo: '/Imagens feriados/Festa junina/FestaJunina1.pdf',
      data: 'Festa Junina',
      descricao: 'Atividade para colorir.',
      salvo: false,
    },
    {
      id: 655,
      titulo: 'Festa Junina',
      imagem: '/Imagens feriados/Festa junina/FestaJunina2.png',
      arquivo: '/Imagens feriados/Festa junina/FestaJunina2.pdf',
      data: 'Festa Junina',
      descricao: 'Atividade para escrever.',
      salvo: false,
    },
    {
      id: 656,
      titulo: 'Festa Junina',
      imagem: '/Imagens feriados/Festa junina/FestaJunina3.png',
      arquivo: '/Imagens feriados/Festa junina/FestaJunina3.pdf',
      data: 'Festa Junina',
      descricao: 'Atividade para cortar e colar.',
      salvo: false,
    },
    {
      id: 657,
      titulo: 'Festa Junina',
      imagem: '/Imagens feriados/Festa junina/FestaJunina4png.png',
      arquivo: '/Imagens feriados/Festa junina/FestaJunina4png.pdf',
      data: 'Festa Junina',
      descricao: 'Atividade para pintar.',
      salvo: false,
    },

    // INDEPENDÊNCIA DO BRASIL
    {
      id: 658,
      titulo: 'Independência do Brasil',
      imagem: '/Imagens feriados/Independencia do Brasil/independenciaDoBR1.png',
      arquivo: '/Imagens feriados/Independencia do Brasil/IndependenciaDoBR1.pdf',
      data: 'Independência do Brasil',
      descricao: 'Atividade para colorir.',
      salvo: false,
    },
    {
      id: 659,
      titulo: 'Independência do Brasil',
      imagem: '/Imagens feriados/Independencia do Brasil/IndependenciaDoBR2.png',
      arquivo: '/Imagens feriados/Independencia do Brasil/IndependenciaDoBR2.pdf',
      data: 'Independência do Brasil',
      descricao: 'Atividade para escrever.',
      salvo: false,
    },
    {
      id: 660,
      titulo: 'Independência do Brasil',
      imagem: '/Imagens feriados/Independencia do Brasil/IndependenciaDoBR3.png',
      arquivo: '/Imagens feriados/Independencia do Brasil/IndependenciaDoBR3.pdf',
      data: 'Independência do Brasil',
      descricao: 'Atividade para cortar e colar.',
      salvo: false,
    },
    // NATAL
    {
      id: 661,
      titulo: 'Natal',
      imagem: '/Imagens feriados/Natal/Natal1.png',
      arquivo: '/Imagens feriados/Natal/Natal1.pdf',
      data: 'Natal',
      descricao: 'Atividade para colorir.',
      salvo: false,
    },
    {
      id: 662,
      titulo: 'Natal',
      imagem: '/Imagens feriados/Natal/Natal2.png',
      arquivo: '/Imagens feriados/Natal/Natal2.pdf',
      data: 'Natal',
      descricao: 'Atividade para escrever.',
      salvo: false,
    },
    {
      id: 663,
      titulo: 'Natal',
      imagem: '/Imagens feriados/Natal/Natal3.png',
      arquivo: '/Imagens feriados/Natal/Natal3.pdf',
      data: 'Natal',
      descricao: 'Atividade para cortar e colar.',
      salvo: false,
    },
    {
      id: 664,
      titulo: 'Natal',
      imagem: '/Imagens feriados/Natal/Natal4.png',
      arquivo: '/Imagens feriados/Natal/Natal4.pdf',
      data: 'Natal',
      descricao: 'Atividade para pintar.',
      salvo: false,
    },
    // PASCOA
    {
      id: 665,
      titulo: 'Páscoa',
      imagem: '/Imagens feriados/Pascoa/pascoa1.png',
      arquivo: '/Imagens feriados/Pascoa/pascoa1.pdf',
      data: 'Páscoa',
      descricao: 'Atividade para colorir.',
      salvo: false,
    },
    {
      id: 666,
      titulo: 'Páscoa',
      imagem: '/Imagens feriados/Pascoa/pascoa2.png',
      arquivo: '/Imagens feriados/Pascoa/pascoa2.pdf',
      data: 'Páscoa',
      descricao: 'Atividade para escrever.',
      salvo: false,
    },
    {
      id: 667,
      titulo: 'Páscoa',
      imagem: '/Imagens feriados/Pascoa/pascoa3.png',
      arquivo: '/Imagens feriados/Pascoa/pascoa3.pdf',
      data: 'Páscoa',
      descricao: 'Atividade para cortar e colar.',
      salvo: false,
    },
    {
      id: 668,
      titulo: 'Páscoa',
      imagem: '/Imagens feriados/Pascoa/pascoa4.png',
      arquivo: '/Imagens feriados/Pascoa/pascoa4.pdf',
      data: 'Páscoa',
      descricao: 'Atividade para pintar.',
      salvo: false,
    },

  ],
})

export default estadoPratica
