import { reactive } from 'vue'

export const estadoPratica = reactive({
  lista: [
    // ANO NOVO
    {
      id: 1,
      titulo: 'Atividade',
      imagem: '/Imagens feriados/Ano Novo/AnoNovo_1.png',
      arquivo: '',
      data: 'Ano Novo',
      descricao: 'Atividade temática para celebração de Ano Novo na educação infantil.',
      salvo: false,
    },
    {
      id: 2,
      titulo: 'Complete o Desenho',
      imagem: '/Imagens feriados/Ano Novo/AnoNovo_2.jpg',
      arquivo: '',
      data: 'Ano Novo',
      descricao: 'Atividade de coordenação motora e escrita para o Ano Novo.',
      salvo: false,
    },
    {
      id: 3,
      titulo: 'Feliz Ano Novo',
      imagem: '/Imagens feriados/Ano Novo/carnaval1.jpg',
      arquivo: '',
      data: 'Ano Novo',
      descricao: 'Desenho e atividade comemorativa de Feliz Ano Novo.',
      salvo: false,
    },

    // CARNAVAL
    {
      id: 4,
      titulo: 'Carnaval Ensino Fundamental 1',
      imagem: '/Imagens feriados/Carnaval/carnaval2.jpg',
      arquivo: '',
      data: 'Carnaval',
      descricao: 'Atividades pedagógicas lúdicas sobre o Carnaval.',
      salvo: false,
    },
    {
      id: 5,
      titulo: 'Atividades para o Carnaval 2022',
      imagem: '/Imagens feriados/Carnaval/carnaval1.png',
      arquivo: '',
      data: 'Carnaval',
      descricao: 'Exercícios práticos e coloridos de Carnaval.',
      salvo: false,
    },
    {
      id: 6,
      titulo: 'Festa de Carnaval',
      imagem: '/Imagens feriados/Carnaval/carnaval.png',
      arquivo: '',
      data: 'Carnaval',
      descricao: 'Ilustrações e atividades artísticas para o Carnaval.',
      salvo: false,
    },
    {
      id: 7,
      titulo: 'Máscaras de Carnaval',
      imagem: '/Imagens feriados/Carnaval/carnaval3.jpg',
      arquivo: '',
      data: 'Carnaval',
      descricao: 'Pintura e confecção de máscaras carnavalescas.',
      salvo: false,
    },
      //colocar atividade
    {
      id: 8,
      titulo: 'Músicas',
      imagem: '/Imagens feriados/Carnaval/',
      arquivo: '',
      data: 'Carnaval',
      descricao: 'Atividade de exploração cultural e ritmos de Carnaval.',
      salvo: false,
    },
      //colocar atividade
    {
      id: 9,
      titulo: 'Cores do Carnaval',
      imagem: '/Imagens feriados/Carnaval/',
      arquivo: '',
      data: 'Carnaval',
      descricao: 'Exercício prático de pintura e colagem para o Carnaval.',
      salvo: false,
    },
      // DIA DA ESCOLA
    {
      id: 10,
      titulo: 'Minha Escola Querida',
      imagem: '/Imagens feriados/Dia da Escola/escola1.png',
      arquivo: '',
      data: 'Dia da Escola',
      descricao: 'Atividades de valorização do ambiente escolar e convívio.',
      salvo: false,
    },
    {
      id: 11,
      titulo: 'Dia da Escola - Educação Infantil',
      imagem: '/Imagens feriados/Dia da Escola/escola2.jpg',
      arquivo: '',
      data: 'Dia da Escola',
      descricao: 'Reconhecimento dos espaços e profissionais da escola.',
      salvo: false,
    },
    {
      id: 12,
      titulo: 'Conhecendo a Escola',
      imagem: '/Imagens feriados/Dia da Escola/escola3.png',
      arquivo: '',
      data: 'Dia da Escola',
      descricao: 'Atividades ilustradas sobre a rotina escolar.',
      salvo: false,
    },
    {
      id: 13,
      titulo: 'Celebrando a Escola',
      imagem: '/Imagens feriados/Dia da Escola/escola4.png',
      arquivo: '',
      data: 'Dia da Escola',
      descricao: 'Desenho e escrita para o Dia da Escola.',
      salvo: false,
    },
    {
      id: 14,
      titulo: 'O Papel da Escola',
      imagem: '/Imagens feriados/Dia da Escola/escola5.jpg',
      arquivo: '',
      data: 'Dia da Escola',
      descricao: 'Reflexão e atividades lúdicas sobre o aprendizado.',
      salvo: false,
    },

    // DIA DA ÁRVORE
    {
      id: 15,
      titulo: 'Preservando as Árvores',
      imagem: '/Imagens feriados/Dia da Árvore/arvore.jpg',
      arquivo: '',
      data: 'Dia da Árvore',
      descricao: 'Conscientização ecológica e cuidados com a natureza.',
      salvo: false,
    },
    {
      id: 16,
      titulo: 'Partes da Árvore',
      imagem: '/Imagens feriados/Dia da Árvore/arvore2.png',
      arquivo: '',
      data: 'Dia da Árvore',
      descricao: 'Identificação de raiz, caule, folhas, flores e frutos.',
      salvo: false,
    },
    {
      id: 17,
      titulo: 'Dia da Árvore - Educação Infantil',
      imagem: '/Imagens feriados/Dia da Árvore/arvore3.jpg',
      arquivo: '',
      data: 'Dia da Árvore',
      descricao: 'Pintura a dedo e colagem temática de árvores.',
      salvo: false,
    },
    {
      id: 18,
      titulo: 'Cuidando da Natureza',
      imagem: '/Imagens feriados/Dia da Árvore/arvore4.jpg',
      arquivo: '',
      data: 'Dia da Árvore',
      descricao: 'Exercícios práticos sobre a importância do meio ambiente.',
      salvo: false,
    },
    {
      id: 19,
      titulo: 'A Importância das Árvores',
      imagem: '/Imagens feriados/Dia da Árvore/arvore5.png',
      arquivo: '',
      data: 'Dia da Árvore',
      descricao: 'Atividade ilustrada sobre oxigênio, sombra e fauna.',
      salvo: false,
    },
    {
      id: 20,
      titulo: 'Viva o Dia da Árvore',
      imagem: '/Imagens feriados/Dia da Árvore/arvore6.jpg',
      arquivo: '',
      data: 'Dia da Árvore',
      descricao: 'Atividade de colorir e completar a árvore.',
      salvo: false,
    },
  ],
})
export default estadoPratica
