import { reactive } from 'vue'

export const estadoPratica = reactive({
  lista: [
    // ANO NOVO
    {
      id: 1,
      titulo: 'Atividade',
      imagem: '/Imagens feriados/Ano Novo/AnoNovo_1.png',
      arquivo: '/Imagens feriados/Ano Novo/AnoNovo_1.pdf',
      data: 'Ano Novo',
      descricao: 'Atividade temática para celebração de Ano Novo na educação infantil.',
      salvo: false,
    },
    {
      id: 2,
      titulo: 'Complete o Desenho',
      imagem: '/Imagens feriados/Ano Novo/AnoNovo_2.jpg',
      arquivo: '/Imagens feriados/Ano Novo/AnoNovo_2.pdf',
      data: 'Ano Novo',
      descricao: 'Atividade de coordenação motora e escrita para o Ano Novo.',
      salvo: false,
    },
    {
      id: 3,
      titulo: 'Feliz Ano Novo',
      imagem: '/Imagens feriados/Ano Novo/AnoNovo_3.jpg',
      arquivo: '/Imagens feriados/Ano Novo/AnoNovo_3.pdf',
      data: 'Ano Novo',
      descricao: 'Desenho e atividade comemorativa de Feliz Ano Novo.',
      salvo: false,
    },

    // CARNAVAL
    {
      id: 4,
      titulo: 'Carnaval Ensino Fundamental 1',
      imagem: '/Imagens feriados/Carnaval/carnaval2.jpg',
      arquivo: '/Imagens feriados/Carnaval/carnaval2.pdf',
      data: 'Carnaval',
      descricao: 'Atividades pedagógicas lúdicas sobre o Carnaval.',
      salvo: false,
    },
    {
      id: 5,
      titulo: 'Atividades para o Carnaval 2022',
      imagem: '/Imagens feriados/Carnaval/carnaval1.png',
      arquivo: '/Imagens feriados/Carnaval/carnaval1.pdf',
      data: 'Carnaval',
      descricao: 'Exercícios práticos e coloridos de Carnaval.',
      salvo: false,
    },
    {
      id: 6,
      titulo: 'Festa de Carnaval',
      imagem: '/Imagens feriados/Carnaval/carnaval.png',
      arquivo: '/Imagens feriados/Carnaval/carnaval.pdf',
      data: 'Carnaval',
      descricao: 'Ilustrações e atividades artísticas para o Carnaval.',
      salvo: false,
    },
    {
      id: 7,
      titulo: 'Máscaras de Carnaval',
      imagem: '/Imagens feriados/Carnaval/carnaval3.jpg',
      arquivo: '/Imagens feriados/Carnaval/carnaval3.pdf',
      data: 'Carnaval',
      descricao: 'Pintura e confecção de máscaras carnavalescas.',
      salvo: false,
    },
    //colocar atividade
    {
      id: 8,
      titulo: 'Músicas',
      imagem: '/Imagens feriados/Carnaval/',
      arquivo: '',
      data: 'Carnaval',
      descricao: 'Atividade de exploração cultural e ritmos de Carnaval.',
      salvo: false,
    },
    //colocar atividade
    {
      id: 9,
      titulo: 'Cores do Carnaval',
      imagem: '/Imagens feriados/Carnaval/',
      arquivo: '',
      data: 'Carnaval',
      descricao: 'Exercício prático de pintura e colagem para o Carnaval.',
      salvo: false,
    },
    // DIA DA ESCOLA
    {
      id: 10,
      titulo: 'Minha Escola Querida',
      imagem: '/Imagens feriados/Dia da Escola/escola1.png',
      arquivo: '/Imagens feriados/Dia da Escola/escola1.pdf',
      data: 'Dia da Escola',
      descricao: 'Atividades de valorização do ambiente escolar e convívio.',
      salvo: false,
    },
    {
      id: 11,
      titulo: 'Dia da Escola - Educação Infantil',
      imagem: '/Imagens feriados/Dia da Escola/escola2.jpg',
      arquivo: '/Imagens feriados/Dia da Escola/escola2.pdf',
      data: 'Dia da Escola',
      descricao: 'Reconhecimento dos espaços e profissionais da escola.',
      salvo: false,
    },
    {
      id: 12,
      titulo: 'Conhecendo a Escola',
      imagem: '/Imagens feriados/Dia da Escola/escola3.png',
      arquivo: '/Imagens feriados/Dia da Escola/escola3.pdf',
      data: 'Dia da Escola',
      descricao: 'Atividades ilustradas sobre a rotina escolar.',
      salvo: false,
    },
    {
      id: 13,
      titulo: 'Celebrando a Escola',
      imagem: '/Imagens feriados/Dia da Escola/escola4.png',
      arquivo: '/Imagens feriados/Dia da Escola/escola4.pdf',
      data: 'Dia da Escola',
      descricao: 'Desenho e escrita para o Dia da Escola.',
      salvo: false,
    },
    {
      id: 14,
      titulo: 'O Papel da Escola',
      imagem: '/Imagens feriados/Dia da Escola/escola5.jpg',
      arquivo: '/Imagens feriados/Dia da Escola/escola5.pdf',
      data: 'Dia da Escola',
      descricao: 'Reflexão e atividades lúdicas sobre o aprendizado.',
      salvo: false,
    },

    // DIA DA ÁRVORE
    {
      id: 15,
      titulo: 'Preservando as Árvores',
      imagem: '/Imagens feriados/Dia da Árvore/arvore.jpg',
      arquivo: '/Imagens feriados/Dia da Árvore/arvore.pdf',
      data: 'Dia da Árvore',
      descricao: 'Conscientização ecológica e cuidados com a natureza.',
      salvo: false,
    },
    {
      id: 16,
      titulo: 'Partes da Árvore',
      imagem: '/Imagens feriados/Dia da Árvore/arvore2.png',
      arquivo: '/Imagens feriados/Dia da Árvore/arvore2.pdf',
      data: 'Dia da Árvore',
      descricao: 'Identificação de raiz, caule, folhas, flores e frutos.',
      salvo: false,
    },
    {
      id: 17,
      titulo: 'Dia da Árvore - Educação Infantil',
      imagem: '/Imagens feriados/Dia da Árvore/arvore3.jpg',
      arquivo: '/Imagens feriados/Dia da Árvore/arvore3.pdf',
      data: 'Dia da Árvore',
      descricao: 'Pintura a dedo e colagem temática de árvores.',
      salvo: false,
    },
    {
      id: 18,
      titulo: 'Cuidando da Natureza',
      imagem: '/Imagens feriados/Dia da Árvore/arvore4.jpg',
      arquivo: '/Imagens feriados/Dia da Árvore/arvore4.pdf',
      data: 'Dia da Árvore',
      descricao: 'Exercícios práticos sobre a importância do meio ambiente.',
      salvo: false,
    },
    {
      id: 19,
      titulo: 'A Importância das Árvores',
      imagem: '/Imagens feriados/Dia da Árvore/arvore5.png',
      arquivo: '/Imagens feriados/Dia da Árvore/arvore5.pdf',
      data: 'Dia da Árvore',
      descricao: 'Atividade ilustrada sobre oxigênio, sombra e fauna.',
      salvo: false,
    },
    {
      id: 20,
      titulo: 'Viva o Dia da Árvore',
      imagem: '/Imagens feriados/Dia da Árvore/arvore6.jpg',
      arquivo: '/Imagens feriados/Dia da Árvore/arvore6.pdf',
      data: 'Dia da Árvore',
      descricao: 'Atividade de colorir e completar a árvore.',
      salvo: false,
    },
    // DIA DAS CRIANÇAS
    {
      id: 21,
      titulo: 'Natureza e Sociedade - Dia das Crianças',
      imagem: '/Imagens feriados/Dia das crianças/criancas1.png',
      arquivo: '/Imagens feriados/Dia das crianças/criancas1.pdf',
      data: 'Dia das Crianças',
      descricao: 'Atividade interdisciplinar sobre direitos e brincadeiras infantis.',
      salvo: false,
    },
    {
      id: 22,
      titulo: 'Direitos da Criança',
      imagem: '/Imagens feriados/Dia das crianças/criancas2.jpg',
      arquivo: '/Imagens feriados/Dia das crianças/criancas2.pdf',
      data: 'Dia das Crianças',
      descricao: 'Exercícios lúdicos e desenhos para o Dia das Crianças.',
      salvo: false,
    },
    {
      id: 23,
      titulo: 'Brincadeiras e Jogos',
      imagem: '/Imagens feriados/Dia das crianças/criancas3.jpg',
      arquivo: '/Imagens feriados/Dia das crianças/criancas3.pdf',
      data: 'Dia das Crianças',
      descricao: 'Atividade de identificação de brinquedos e brincadeiras.',
      salvo: false,
    },
    // DIA DAS MÃES
    {
      id: 24,
      titulo: 'Cartão para o Dia das Mães 1',
      imagem: '/Imagens feriados/Dia das Maes/DiasDasMaes1.png',
      arquivo: '/Imagens feriados/Dia das Maes/DiasDasMaes1.pdf',
      data: 'Dia das Mães',
      descricao: 'Produção de mensagem e cartão afetivo para as mães.',
      salvo: false,
    },
    {
      id: 25,
      titulo: 'Cartão para o Dia das Mães 2',
      imagem: '/Imagens feriados/Dia das Maes/DiasDasMaes2.png',
      arquivo: '/Imagens feriados/Dia das Maes/DiasDasMaes2.pdf',
      data: 'Dia das Mães',
      descricao: 'Atividade de desenho e colagem para homenagear as mães.',
      salvo: false,
    },
    {
      id: 26,
      titulo: 'Poema do Dia das Mães',
      imagem: '/Imagens feriados/Dia das Maes/DiasDasMaes4.png',
      arquivo: '/Imagens feriados/Dia das Maes/DiasDasMaes4.pdf',
      data: 'Dia das Mães',
      descricao: 'Leitura, interpretação e pintura especial para o Dia das Mães.',
      salvo: false,
    },
    //colocar atividade
    {
      id: 27,
      titulo: 'Retrato da Mamãe',
      imagem: '/Imagens feriados/Dia das Maes/',
      arquivo: '',
      data: 'Dia das Mães',
      descricao: 'Atividade criativa de desenho do rosto da mãe.',
      salvo: false,
    },

    // DIA DO AMIGO
    {
      id: 28,
      titulo: 'Amigos Especiais',
      imagem: '/Imagens feriados/Dia do Amigo/amigos_atividade1.jpg',
      arquivo: '/Imagens feriados/Dia do Amigo/amigos_atividade1.pdf',
      data: 'Dia do Amigo',
      descricao: 'Atividade sobre amizade, respeito e convivência.',
      salvo: false,
    },
    {
      id: 29,
      titulo: 'Dia do Amigo e da Amizade',
      imagem: '/Imagens feriados/Dia do Amigo/amigos_atividade2.jpg',
      arquivo: '/Imagens feriados/Dia do Amigo/amigos_atividade2.pdf',
      data: 'Dia do Amigo',
      descricao: 'Exercícios práticos de empatia e união entre colegas.',
      salvo: false,
    },
    {
      id: 30,
      titulo: 'Amizade na Escola',
      imagem: '/Imagens feriados/Dia do Amigo/amigos_atividade3.jpg',
      arquivo: '/Imagens feriados/Dia do Amigo/amigos_atividade3.pdf',
      data: 'Dia do Amigo',
      descricao: 'Dinâmica e pintura coletiva sobre amigos.',
      salvo: false,
    },
    {
      id: 31,
      titulo: 'Complete a Palavra Amigo',
      imagem: '/Imagens feriados/Dia do Amigo/amigos_atividade4.jpg',
      arquivo: '/Imagens feriados/Dia do Amigo/amigos_atividade4.pdf',
      data: 'Dia do Amigo',
      descricao: 'Atividade de alfabetização e escrita da palavra amigo.',
      salvo: false,
    },
    // DIA DOS ANIMAIS
    {
      id: 32,
      titulo: 'Amigos da Natureza',
      imagem: '/Imagens feriados/Dia dos Animais/animais1.jpg',
      arquivo: '/Imagens feriados/Dia dos Animais/animais1.pdf',
      data: 'Dia dos Animais',
      descricao: 'Atividade sobre amizade, respeito e convivência.',
      salvo: false,
    },
    {
      id: 33,
      titulo: 'Dia do Amigo e da Amizade',
      imagem: '/Imagens feriados/Dia dos Animais/animais2.jpg',
      arquivo: '/Imagens feriados/Dia dos Animais/animais2.pdf',
      data: 'Dia dos Animais',
      descricao: 'Exercícios práticos de empatia e união entre colegas.',
      salvo: false,
    },
    {
      id: 34,
      titulo: 'Amizade na Escola',
      imagem: '/Imagens feriados/Dia dos Animais/animais3.jpg',
      arquivo: '/Imagens feriados/Dia dos Animais/animais3.pdf',
      data: 'Dia dos Animais',
      descricao: 'Dinâmica e pintura coletiva sobre amigos.',
      salvo: false,
    },
    {
      id: 35,
      titulo: 'Complete a Palavra Amigo',
      imagem: '/Imagens feriados/Dia dos Animais/animais4.png',
      arquivo: '/Imagens feriados/Dia dos Animais/animais4.pdf',
      data: 'Dia dos Animais',
      descricao: 'Atividade de alfabetização e escrita da palavra amigo.',
      salvo: false,
    },
    {
      id: 36,
      titulo: 'Complete a Palavra Amigo',
      imagem: '/Imagens feriados/Dia dos Animais/animais5.jpg',
      arquivo: '/Imagens feriados/Dia dos Animais/animais5.pdf',
      data: 'Dia dos Animais',
      descricao: 'Atividade de alfabetização e escrita da palavra amigo.',
      salvo: false,
    },
    // DIA DOS PAIS
    {
      id: 37,
      titulo: 'Dia dos Pais',
      imagem: '/Imagens feriados/Dia dos Pais/pais1.jpg',
      arquivo: '/Imagens feriados/Dia dos Pais/pais1.pdf',
      data: 'Dia dos Pais',
      descricao: 'Atividade sobre o Dia dos Pais.',
      salvo: false,
    },
    {
      id: 38,
      titulo: 'Mãe e Pai',
      imagem: '/Imagens feriados/Dia dos Pais/pais2 .jpg',
      arquivo: '/Imagens feriados/Dia dos Pais/pais2.pdf',
      data: 'Dia dos Pais',
      descricao: 'Atividade sobre o Dia dos Pais.',
      salvo: false,
    },
    // DIA DOS POVOS INDÍGENAS
    {
      id: 39,
      titulo: 'Povos Indígenas',
      imagem: '/Imagens feriados/Dia dos Povos Indígenas/povosIndigenas1.jpg',
      arquivo: '/Imagens feriados/Dia dos Povos Indígenas/povosIndigenas1.pdf',
      data: 'Dia dos Povos Indígenas',
      descricao: 'Atividade para colorir.',
      salvo: false,
    },
    {
      id: 40,
      titulo: 'Povos Indígenas',
      imagem: '/Imagens feriados/Dia dos Povos Indígenas/povosIndigenas2.jpg',
      arquivo: '/Imagens feriados/Dia dos Povos Indígenas/povosIndigenas2.pdf',
      data: 'Dia dos Povos Indígenas',
      descricao: 'Atividade para escrever.',
      salvo: false,
    },
    {
      id: 41,
      titulo: 'Povos Indígenas',
      imagem: '/Imagens feriados/Dia dos Povos Indígenas/povosIndigenas3.jpg',
      arquivo: '/Imagens feriados/Dia dos Povos Indígenas/povosIndigenas3.pdf',
      data: 'Dia dos Povos Indígenas',
      descricao: 'Atividade para cortar e colar.',
      salvo: false,
    },
    // DIA INTERNACIONAL DA MULHER
    {
      id: 42,
      titulo: 'Dia Internacional da Mulher',
      imagem: '/Imagens feriados/Dia Internacional da Mulher/diaMulher1.jpg',
      arquivo: '/Imagens feriados/Dia Internacional da Mulher/diaMulher1.pdf',
      data: 'Dia Internacional da Mulher',
      descricao: 'Atividade para colorir.',
      salvo: false,
    },
    {
      id: 43,
      titulo: 'Dia Internacional da Mulher',
      imagem: '/Imagens feriados/Dia Internacional da Mulher/diaMulher2.jpg',
      arquivo: '/Imagens feriados/Dia Internacional da Mulher/diaMulher2.pdf',
      data: 'Dia Internacional da Mulher',
      descricao: 'Atividade para escrever.',
      salvo: false,
    },
    {
      id: 44,
      titulo: 'Dia Internacional da Mulher',
      imagem: '/Imagens feriados/Dia Internacional da Mulher/diaMulher3.png',
      arquivo: '/Imagens feriados/Dia Internacional da Mulher/diaMulher3.pdf',
      data: 'Dia Internacional da Mulher',
      descricao: 'Atividade para cortar e colar.',
      salvo: false,
    },
    {
      id: 45,
      titulo: 'Dia Internacional da Mulher',
      imagem: '/Imagens feriados/Dia Internacional da Mulher/diaMulher4.jpg',
      arquivo: '/Imagens feriados/Dia Internacional da Mulher/diaMulher4.pdf',
      data: 'Dia Internacional da Mulher',
      descricao: 'Atividade para pintar.',
      salvo: false,
    },
    // DIA MUNDIAL DO TRABALHO
    {
      id: 46,
      titulo: 'Dia Mundial do Trabalho',
      imagem: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho1.jpg',
      arquivo: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho1.pdf',
      data: 'Dia Mundial do Trabalho',
      descricao: 'Atividade para colorir.',
      salvo: false,
    },
    {
      id: 47,
      titulo: 'Dia Mundial do Trabalho',
      imagem: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho2.jpg',
      arquivo: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho2.pdf',
      data: 'Dia Mundial do Trabalho',
      descricao: 'Atividade para escrever.',
      salvo: false,
    },
    {
      id: 48,
      titulo: 'Dia Mundial do Trabalho',
      imagem: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho3.jpg',
      arquivo: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho3.pdf',
      data: 'Dia Mundial do Trabalho',
      descricao: 'Atividade para cortar e colar.',
      salvo: false,
    },
    {
      id: 49,
      titulo: 'Dia Mundial do Trabalho',
      imagem: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho4.png',
      arquivo: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho4.pdf',
      data: 'Dia Mundial do Trabalho',
      descricao: 'Atividade para pintar.',
      salvo: false,
    },
    {
      id: 50,
      titulo: 'Dia Mundial do Trabalho',
      imagem: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho5.jpeg',
      arquivo: '/Imagens feriados/Dia Mundial do Trabalho/diaTrabalho5.pdf',
      data: 'Dia Mundial do Trabalho',
      descricao: 'Atividade para pintar.',
      salvo: false,
    },
    // DIA MUNDIAL DOS PROFESSORES
    {
      id: 51,
      titulo: 'Dia Mundial dos Professores',
      imagem: '/Imagens feriados/Dia Mundial dos Professores/diaProfessor1.jpg',
      arquivo: '/Imagens feriados/Dia Mundial dos Professores/diaProfessor1.pdf',
      data: 'Dia Mundial dos Professores',
      descricao: 'Atividade para colorir.',
      salvo: false,
    },
    {
      id: 52,
      titulo: 'Dia Mundial dos Professores',
      imagem: '/Imagens feriados/Dia Mundial dos Professores/diaProfessor2.png',
      arquivo: '/Imagens feriados/Dia Mundial dos Professores/diaProfessor2.pdf',
      data: 'Dia Mundial dos Professores',
      descricao: 'Atividade para escrever.',
      salvo: false,
    },
    // FESTA JUNINA
    {
      id: 53,
      titulo: 'Festa Junina',
      imagem: '/Imagens feriados/Festa Junina/FestaJunina1.png',
      arquivo: '/Imagens feriados/Festa Junina/FestaJunina1.pdf',
      data: 'Festa Junina',
      descricao: 'Atividade para colorir.',
      salvo: false,
    },
    {
      id: 54,
      titulo: 'Festa Junina',
      imagem: '/Imagens feriados/Festa Junina/FestaJunina2.png',
      arquivo: '/Imagens feriados/Festa Junina/FestaJunina2.pdf',
      data: 'Festa Junina',
      descricao: 'Atividade para escrever.',
      salvo: false,
    },
    {
      id: 55,
      titulo: 'Festa Junina',
      imagem: '/Imagens feriados/Festa Junina/FestaJunina3.png',
      arquivo: '/Imagens feriados/Festa Junina/FestaJunina3.pdf',
      data: 'Festa Junina',
      descricao: 'Atividade para cortar e colar.',
      salvo: false,
    },
    {
      id: 56,
      titulo: 'Festa Junina',
      imagem: '/Imagens feriados/Festa Junina/FestaJunina4.png',
      arquivo: '/Imagens feriados/Festa Junina/FestaJunina4.pdf',
      data: 'Festa Junina',
      descricao: 'Atividade para pintar.',
      salvo: false,
    },

    // INDEPENDÊNCIA DO BRASIL
    {
      id: 57,
      titulo: 'Independência do Brasil',
      imagem: '/Imagens feriados/Independência do Brasil/IndependenciaDoBR1.png',
      arquivo: '/Imagens feriados/Independência do Brasil/IndependenciaDoBR1.pdf',
      data: 'Independência do Brasil',
      descricao: 'Atividade para colorir.',
      salvo: false,
    },
    {
      id: 58,
      titulo: 'Independência do Brasil',
      imagem: '/Imagens feriados/Independência do Brasil/IndependenciaDoBR2.png',
      arquivo: '/Imagens feriados/Independência do Brasil/IndependenciaDoBR2.pdf',
      data: 'Independência do Brasil',
      descricao: 'Atividade para escrever.',
      salvo: false,
    },
    {
      id: 59,
      titulo: 'Independência do Brasil',
      imagem: '/Imagens feriados/Independência do Brasil/IndependenciaDoBR3.png',
      arquivo: '/Imagens feriados/Independência do Brasil/IndependenciaDoBR3.pdf',
      data: 'Independência do Brasil',
      descricao: 'Atividade para cortar e colar.',
      salvo: false,
    },
    // NATAL
    {
      id: 60,
      titulo: 'Natal',
      imagem: '/Imagens feriados/Natal/Natal1.png',
      arquivo: '/Imagens feriados/Natal/Natal1.pdf',
      data: 'Natal',
      descricao: 'Atividade para colorir.',
      salvo: false,
    },
    {
      id: 61,
      titulo: 'Natal',
      imagem: '/Imagens feriados/Natal/Natal2.png',
      arquivo: '/Imagens feriados/Natal/Natal2.pdf',
      data: 'Natal',
      descricao: 'Atividade para escrever.',
      salvo: false,
    },
    {
      id: 62,
      titulo: 'Natal',
      imagem: '/Imagens feriados/Natal/Natal3.png',
      arquivo: '/Imagens feriados/Natal/Natal3.pdf',
      data: 'Natal',
      descricao: 'Atividade para cortar e colar.',
      salvo: false,
    },
    {
      id: 63,
      titulo: 'Natal',
      imagem: '/Imagens feriados/Natal/Natal4.png',
      arquivo: '/Imagens feriados/Natal/Natal4.pdf',
      data: 'Natal',
      descricao: 'Atividade para pintar.',
      salvo: false,
    },
    // PASCOA
    {
      id: 64,
      titulo: 'Páscoa',
      imagem: '/Imagens feriados/Páscoa/pascoa1.png',
      arquivo: '/Imagens feriados/Páscoa/pascoa1.pdf',
      data: 'Páscoa',
      descricao: 'Atividade para colorir.',
      salvo: false,
    },
    {
      id: 65,
      titulo: 'Páscoa',
      imagem: '/Imagens feriados/Páscoa/pascoa2.png',
      arquivo: '/Imagens feriados/Páscoa/pascoa2.pdf',
      data: 'Páscoa',
      descricao: 'Atividade para escrever.',
      salvo: false,
    },
    {
      id: 66,
      titulo: 'Páscoa',
      imagem: '/Imagens feriados/Páscoa/pascoa3.png',
      arquivo: '/Imagens feriados/Páscoa/pascoa3.pdf',
      data: 'Páscoa',
      descricao: 'Atividade para cortar e colar.',
      salvo: false,
    },
    {
      id: 67,
      titulo: 'Páscoa',
      imagem: '/Imagens feriados/Páscoa/pascoa4.png',
      arquivo: '/Imagens feriados/Páscoa/pascoa4.pdf',
      data: 'Páscoa',
      descricao: 'Atividade para pintar.',
      salvo: false,
    },
  ],
})

export default estadoPratica
